apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
spec:
  dnsNames:
    - backstage-janus-idp.apps.janus-idp.w6gk.p1.openshiftapps.com
  issuerRef:
    name: letsencrypt
  secretName: janus-idp-cert
