site_name: backstage-showcase
site_description: 'User documentation for Janus Showcase'
repo_url: https://github.com/janus-idp/backstage-showcase
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Overview: index.md
  - Onboard a developer to Openshift: onboard_openshift.md
  - Application Migration:
      - Migration Process Overview: application_migration/migration_process_overview.md
      - Migration Process Steps: application_migration/migration_process_steps.md
      - Learning Path for Developers: application_migration/learning-path-for-developers.md
