apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
spec:
  dnsNames:
    - keycloak.apps.janus-idp.w6gk.p1.openshiftapps.com
  issuerRef:
    name: letsencrypt
  secretName: keycloak-cert
